[32mINFO    [0m root:logger.py:30 用户名或密码错误
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (1): 127.0.0.1:8888
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://127.0.0.1:8888 "POST /loginjosn HTTP/1.1" 200 51